mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springmvc-mybatis
    username: root
    password: gys
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8082
  context-path: /test
myconfig: gys
age: 25
content: "myname:${myconfig},age:${age}"
myconfig1:
  name: gysssssdddd
  age: 35


